steps:
  - id: "Running docker-compose"
    name: "gcr.io/$PROJECT_ID/docker-compose:1.25.5"
    args: ['-f', 'docker-compose.cloud.yaml', 'up', '-d']
    
  - id: "Running docker ps"
    name: "gcr.io/cloud-builders"
    args: ['ps']